function detectorDistances = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DETECTORDISTANCES = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DETECTORDISTANCES = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  detectorDistances = importfile("C:\Users\black\OneDrive\matlab\detectorDistances.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Apr-2022 19:44:25

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Config", "det1", "det2", "z2", "z3"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
detectorDistances = readtable(filename, opts);

end