function collisions = importfile2tab(filename, dataLines)
%IMPORTFILE Import data from a text file
%  COLLISIONS = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  COLLISIONS = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  collisions = importfile2tab("C:\Users\black\Downloads\Geant4\matlab\200_collisions.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Mar-2022 17:25:18

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["collisionNum", "Secondary", "p_x", "p_y", "p_z", "mass_energy_MeV"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["collisionNum", "Secondary"], "EmptyFieldRule", "auto");

% Import the data
collisions = readtable(filename, opts);

end